# This is a basic workflow to help you get started with Actions

name: CI Deployment to Studioz

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a HTTP request to Twilio Flows V2 API ss
            
      - name: Make Twilio API Reguest
        id: updateFlowz
        run: | 
            DEFINITION=$(cat ./studio.json)
            echo $DEFINITION
            #StatusCode=$(awk 'BEGIN {"curl -sI -X POST https://studio.twilio.com/v2/Flows/${{ secrets.PROD_FLOW_SID }} \ --data-urlencode "CommitMessage=Prod release v2" \ --data-urlencode "Definition=$DEFINITION"  --data-urlencode "Status=published"  -u ${{ secrets.PROD_ACCOUNT_SID }}:${{ secrets.PROD_AUTH_KEY }}" | getline; print "Status Code: " $2}')
            #STATUSCODE=$(awk 'BEGIN {"curl -sI http://example.com" | getline; print "Status Code: " $2}')  
            #STATUSCODE=$(awk 'BEGIN {"curl -X POST https://studio.twilio.com/v2/Flows/${{ secrets.PROD_FLOW_SID }} --data-urlencode "CommitMessage=Prod release v2" --data-urlencode "Definition=$DEFINITION"  --data-urlencode "Status=published"  -u ${{ secrets.PROD_ACCOUNT_SID }}:${{ secrets.PROD_AUTH_KEY }}" | getline; print "Status Code: " $2}')
            echo STATUSCODE=$(awk 'BEGIN {"curl -X POST -sI https://studio.twilio.com/v2/Flows/FW2e5c1733339c291a3d9119110c58e87f  --data-urlencode "CommitMessage=Prod release v2" --data-urlencode "Definition=$DEFINITION" --data-urlencode "Status=published" -u ${{ secrets.PROD_ACCOUNT_SID }}:${{ secrets.PROD_AUTH_KEY }}" | getline; print $2}')
            echo $STATUSCODE   
      
