# This is a basic workflow to help you get started with Actions

name: CI Deployment to Studioz

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a HTTP request to Twilio Flows V2 API
            
      - name: Make Twilio API Reguest
        id: updateFlow
        run: | 
            DEFINITION=$(cat ./studio.json)
            echo $DEFINITION
            STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}"  -X POST  --data-urlencode "CommitMessage=Prod release v2" --data-urlencode "Definition=$DEFINITION"  --data-urlencode "Status=published" -u ${{ secrets.PROD_ACCOUNT_SID }}:${{ secrets.PROD_AUTH_KEY }}  https://studio.twilio.com/v2/Flows/${{ secrets.PROD_FLOW_SID }}` >> $GITHUB_ENV
            echo $STATUS_CODE
        
     
      - name: if Condition
        if: success()
        run: |
          echo $STATUS_CODE
          EXECUTION_STATUS=`curl -s -o -i /dev/null -w "%{http_code}"  -X POST --data-urlencode "To=+16318721739" --data-urlencode "From=+16312502963"  -u ${{ secrets.PROD_ACCOUNT_SID }}:${{ secrets.PROD_AUTH_KEY }} https://studio.twilio.com/v2/Flows/${{ secrets.PROD_FLOW_SID }}/Executions` 
          echo $EXECUTION_STATUS

      - name: rollback Condition
        if: failure()
        run: |
          echo "rollback"
          
      
